card_project/cards/cards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('trading/', include('trading.urls')),
    path('forum/', include('forum.urls')),
    path('admin_app/', include('admin_app.urls')),
]

card_project/cards/trading/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.TransactionListView.as_view(), name='home'),
    path('create_trade/', views.CreateTradeView.as_view(), name='create_trade'),
    path('trade_response/<int:pk>/<str:status>/', views.update_trade_status, name='trade_response'),
    path('trade_response_status/<int:pk>/<str:status>/', views.update_trade_back_status, name='trade_response_status'),
    path('trade_response/<int:pk>/', views.TradeResponseView.as_view(), name='trade_response_back'),
    path('trade_details/<int:pk>/', views.TradeDetailView.as_view(), name='trade_details'),
    path('store', views.StoreView.as_view(), name='store'),
    path('card_details/<int:pk>/', views.CardDetailView.as_view(), name='card_details'),
    path('offer_sale/', views.SellCardView.as_view(), name='offer_sale'),
    path('card_sales/', views.SellTransactionListView.as_view(), name='card_sales'),
    path('sell_card/<int:pk>/', views.sell_card_to_store, name='sell_card'),
    path('offer_card_status/<int:pk>/<str:status>/', views.buy_card, name='offer_card_status'),
    path('offer_card_status/<int:pk>/', views.buy_card_from_store, name='buy_card_from_store'),
    path('get_user_to_sell/<int:pk>/', views.get_user_to_sell, name='get_user_to_sell'),
]

card_project/cards/trading/models.py
from accounts.models import Profile
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE, PROTECT
import random
from django import forms

class Card(models.Model):
    CARD_CHOICES = [
        ('P', 'People Card'),
        ('V', 'Vehicle Card')
    ]
    name = models.CharField(max_length=50,  default=1)
    c_type = models.CharField(choices=CARD_CHOICES, max_length=2)
    owners = models.ManyToManyField('accounts.Profile', related_name='deck')
    rarity = models.IntegerField(default=0)
    price = models.IntegerField(default=50)
    min_score_buy = models.IntegerField(default=200)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.name

    @classmethod
    def deal(cls):
        vehicle_cards = cls.objects.filter(c_type='V', quantity=1).order_by('rarity')
        people_cards = cls.objects.filter(c_type='P', quantity=1).order_by('rarity')
        deck = random.sample(list(vehicle_cards), k=6) + random.sample(list(people_cards), k=6)
        return deck


class PeopleCard(Card):
    height  = models.IntegerField()
    home_world = models.CharField(max_length=50)
    mass = models.IntegerField()


class VehicleCard(Card):
    model   = models.CharField(max_length=50)
    vehicle_class  = models.CharField(max_length=50)
    max_atmosphering_speed = models.IntegerField()

TRADE_CHOICES = [
    ('A', 'ACCEPT'),
    ('R', 'REJECT'),
    ('P','PENDING'),
    ('C', 'COMPLETED')
]

class Transaction(models.Model):
    trade_sender = models.ForeignKey('accounts.Profile', on_delete=CASCADE, related_name='my_offer')
    trade_reciever = models.ForeignKey('accounts.Profile', related_name='offer_target',  on_delete=CASCADE, null=True)
    card = models.ForeignKey(Card, on_delete=CASCADE, related_name='card1', default=1)
    choice = models.CharField(choices=TRADE_CHOICES, default='P', max_length=10) 
    trade_choice = models.BooleanField(null=True)
    timestamp = models.DateTimeField(auto_now=True)


class TransactionResponse(models.Model):
    card = models.ForeignKey(Card, on_delete=CASCADE, related_name='trades_respone', default=1)
    original_transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE, null=True)
    trade_choice = models.BooleanField(null=True)

    def swap_cards(self):
        if self.original_transaction.trade_choice and self.trade_choice:
            self.original_transaction.choice = "C"
            return True
        else:
            return False

class SellCardTransaction(models.Model):
    seller = models.ForeignKey('accounts.Profile', on_delete=CASCADE, related_name='seller')
    buyer = models.ForeignKey('accounts.Profile', related_name='buyer',  on_delete=CASCADE, null=True)
    card = models.ForeignKey(Card, on_delete=CASCADE, related_name='card_sell', default=1)
    choice = models.CharField(choices=TRADE_CHOICES, default='P', max_length=10) 
    trade_choice = models.BooleanField(null=True)
    timestamp = models.DateTimeField(auto_now=True)

card_project/cards/trading/forms.py
from django import forms
from .models import Transaction, TransactionResponse, SellCardTransaction
from django.contrib.auth.models import User
from trading.models import Card

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['card']
        
class TransactionResponseForm(forms.ModelForm):
    class Meta:
        model = TransactionResponse
        fields = ['card']
        

class SellCardTransactionForm(forms.ModelForm):

    class Meta:
        model = SellCardTransaction
        fields = ['card']

card_project/cards/trading/views.py
from admin_app.models import Store
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import TransactionForm, TransactionResponseForm, SellCardTransactionForm
from .models import Card, Transaction, TransactionResponse, SellCardTransaction
from accounts.models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django import forms

class TransactionListView(LoginRequiredMixin,ListView):
    model = Transaction
    template_name = 'trading/home.html'

class TradeDetailView(LoginRequiredMixin, DetailView):
    model = Transaction
    template_name = 'trading/trade_details.html'

class TradeResponseView(LoginRequiredMixin, CreateView):
    form_class = TransactionResponseForm
    template_name = 'trading/trade_response.html'
    success_url = reverse_lazy('home')

    def get_trade(self):
        thread_id = self.kwargs['pk']
        return get_object_or_404(Transaction, id=thread_id)

    def form_valid(self, form): 
        transaction_response = form.save(commit=False)
        transaction_response.original_transaction = self.get_trade()
        transaction_response.save()
        print(transaction_response)
        return super().form_valid(form)

        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        original_transaction = self.get_trade()
        sender = original_transaction.trade_sender.deck.all()
        reciever = original_transaction.trade_reciever.deck.all()
        dif = list(set(reciever) - set(sender))
        context['trade_options'] = dif # get the options for trade for user
        context['trade_sender'] = self.get_trade().trade_sender
        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['card'].queryset = self.request.user.profile.deck.all()
        return form
    
@login_required
def update_trade_status(request, pk, status):
    transaction = get_object_or_404(Transaction, id=pk)
    card = transaction.card
    user = Profile.objects.get(id=transaction.trade_sender.id)
    if status == 'accept':
        transaction.trade_choice = 1
        transaction.trade_reciever = request.user.profile
        if not transaction.trade_reciever.deck.filter(id = Card.objects.get(id=card.id).id).exists(): 
            transaction.choice = 'A'
            transaction.save()
            return redirect('trade_response_back', pk)
        else:
            transaction.trade_choice = 0
            transaction.save()
            messages.error(request, 'You already have that card, you can\'t have duplicates trade rejected')
            return redirect('home')

    else:
        user.score -= 5
        user.save()
        transaction.trade_choice = 0
        transaction.save()
        return redirect('home')

@login_required
def update_trade_back_status(request, pk, status):
    transaction = get_object_or_404(TransactionResponse, id=pk)
    first_trans = transaction.original_transaction
    second_trans = transaction
    user1 = Profile.objects.get(id=first_trans.trade_sender.id)
    user2 = Profile.objects.get(id=second_trans.original_transaction.trade_reciever.id)
    card1 = first_trans.card
    card2 = second_trans.card
    if status == 'accept':
        if not user1.deck.filter(id = Card.objects.get(id=card2.id).id).exists():
            transaction.trade_choice = 1
            print(transaction.original_transaction.choice)
            if transaction.swap_cards():
                print(user1, 'user1')
                print(user2, 'user2')
                print(first_trans.card, 'first_trans.card')
                print(second_trans.card, 'secontrans.card')
                print(card1, 'card1')
                print(card2, 'card2')
                print(user1.deck.all(), 'before1')
                print(user2.deck.all(), 'before2')
                user1.deck.add(card2) 
                user1.deck.remove(card1) 
                user2.deck.add(card1)
                user2.deck.remove(card2)
                transaction.save()
                user1.coins += 10
                user2.coins += 10
                user1.score += 10
                user2.score += 10
                user1.save()
                user2.save()
                print(user1.deck.all(), 'after1')
                print(user2.deck.all(), 'after2')
                messages.success(request, 'trade was succesfull! score+10 coins+10')
                return redirect('home')
        else:
            user1.score -= 5
            user2.score -= 5
            user1.save()
            user2.save()
            transaction.trade_choice = 0
            transaction.save()
            messages.error(request, 'You already have that card, you can\'t have duplicates. trade rejected -5 points')
            return redirect('home')
    else:
        user1.score -= 5
        user1.save()
        print('asd')
        transaction.trade_choice = 0
        transaction.save()
    return redirect('home')



class CreateTradeView(LoginRequiredMixin, CreateView):
    form_class = TransactionForm
    template_name = 'trading/create_trade.html'
    success_url = reverse_lazy('home')

    

    def form_valid(self, form): 
        transaction = form.save(commit=False)
        transaction.trade_sender = self.request.user.profile
        transaction.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cards'] = self.request.user.profile.deck.all()
        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['card'].queryset = self.request.user.profile.deck.all()
        return form


class StoreView(LoginRequiredMixin, ListView):
    model = Store
    template_name = 'trading/store.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cards_li = [card for card in Store.objects.all() if card.quantity > 0]
        context['cards'] = cards_li
        return context

class CardDetailView(LoginRequiredMixin, DetailView):
    model = Card
    template_name = 'trading/card_details.html'
    success_url = reverse_lazy('home')

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['card'].queryset = self.request.user.profile.deck.all()
        return form



def sell_card_to_store(request, pk):
    card = get_object_or_404(Card, id=pk)
    user = request.user.profile
    user_deck = user.deck
    if len(user_deck.all()) > 12:
        user_deck.remove(card)
        user.coins += card.price - (card.price / 10)
        user.save()
        messages.success(request, 'Card sold.')
    else:
        messages.error(request, 'You can\'t have less than 12 cards.')
    
    return redirect('profile')

#  BuyCardResponseForm, SellCardTransactionForm

def get_user_to_sell(request, pk):
    user = get_object_or_404(Profile, id=pk)
    print(user.is_seller_deck_valid())
    if user.is_seller_deck_valid():
        return redirect('offer_sale')
    else:
        messages.error(request, 'you can\'t sell if you have 12 or less cards')
        return redirect('profile')



class UserDeckRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.profile.is_seller_deck_valid()

class SellCardView(UserDeckRequiredMixin, CreateView):
    form_class = SellCardTransactionForm
    template_name = 'trading/sell_card.html'
    success_url = reverse_lazy('card_sales')

    def form_valid(self, form): 
        transaction = form.save(commit=False)
        transaction.seller = self.request.user.profile
        transaction.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['card'].queryset = self.request.user.profile.deck.all()
        return form


class SellTransactionListView(LoginRequiredMixin,ListView):
    model = SellCardTransaction
    template_name = 'trading/selling.html'


@login_required
def buy_card(request, pk, status):
    transaction = get_object_or_404(SellCardTransaction, id=pk)
    card = transaction.card
    seller = Profile.objects.get(id=transaction.seller.id)
    if status == 'accept':
        transaction.trade_choice = 1
        transaction.buyer = request.user.profile
        if len(transaction.buyer.deck.all()) <= 14:
            if not transaction.buyer.deck.filter(id = Card.objects.get(id=card.id).id).exists():
                if transaction.buyer.coins >= card.price:
                    seller.deck.remove(card)
                    seller.coins += card.price
                    transaction.buyer.coins -= card.price
                    transaction.buyer.deck.add(card)
                    print(seller, 'seller')
                    print(transaction.buyer, 'buyer')
                    print(card.price)
                    seller.save()
                    transaction.buyer.save()
                    transaction.save()
                    messages.success(request, f'you bought {card}')
                    return redirect('profile')
            
                else:
                    transaction.trade_choice = 0
                    transaction.save()
                    messages.error(request, 'you don\'t have enough coins. trade rejected')
                    return redirect('home')

            else:
                transaction.trade_choice = 0
                transaction.save()

card_project/cards/trading/templates/trading/card_details.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

    <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
            <ul>
                {% if card.c_type == 'P' %}
                    <h5 class="card-title">Category: People</h5>
                {% else %}
                    <h5 class="card-title">Category: Vehicles</h5>
                {% endif %}
                <p class="card-text">Name: {{card}}</p>
                <p class="card-text">Rarity: {{card.rarity}}</p>
                <p class="card-text">Id: {{card.id}}</p>
                <p class="card-text">Price: {{card.price}}</p>
            </ul>

          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        
        </div>
      </div>
{% endblock %}

card_project/cards/trading/templates/trading/create_trade.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
<ul class="messages">
    <h1>buy</h1>
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
    <h1>Trade</h1>
    <form method="POST">
        {% csrf_token %} 
        {{form.as_p}}

        <button class='btn btn-success' type="submit">Save</button>
    </form>
{% endblock %}

card_project/cards/trading/templates/trading/home.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
    <h1>hello</h1>
    {% if user.is_authenticated %}
    <div class="container">
        <div class="row">
    {% for transaction in object_list %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Sender: {% if not transaction.trade_sender == user.profile %}{{transaction.trade_sender}}{% else %} You {% endif %}</h5>
                    <h5 class="card-title">Card: {{transaction.card}}</h5>
                    <h5 class="card-title">Time Created: {{transaction.timestamp}}</h5>
                    {% if transaction.choice == 'A' %}
                    <a href="#" aria-disabled="true" class='btn btn-success' type="submit">Accepted</a>
                    <a href="{% url 'trade_details' transaction.id  %}" class='btn btn-success' name='a' type="submit">Status</a>
                    {% elif transaction.choice == 'C'%}
                    <a aria-disabled="true" class='btn btn-warning' type="submit">Completed</a>
                    {% elif transaction.trade_choice == None %}
                    <a aria-disabled="true" class='btn btn-warning' type="submit">Pending</a>
                        {% if not transaction.trade_sender == user.profile %}
                        <a href="{% url 'trade_response' transaction.id 'accept' %}" class='btn btn-success' name='a' type="submit">Accept</a>
                        <a href="{% url 'trade_response' transaction.id 'reject' %}" class='btn btn-danger' name='a' type="submit">Reject</a>
                        {% endif %}
                    {% elif transaction.trade_choice == 1 %}
                    <a href="#" aria-disabled="true" class='btn btn-success' type="submit">Accepted</a>
                    <a href="{% url 'trade_response_back' transaction.id  %}" class='btn btn-success' name='a' type="submit">Offer Back</a>
                    <a href="{% url 'trade_details' transaction.id  %}" class='btn btn-success' name='a' type="submit">Status</a>
                    {% elif transaction.trade_choice == 0 %}
                    <a href="#" aria-disabled="true" class='btn btn-danger' type="submit">Rejected</a>
                    {% endif %}
                    {% if user.is_superuser %}
                    <a href="{% url 'delete_trade' transaction.id %}" class="btn btn-danger">Delete Trade</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endif %}

{% endblock %}

{% for transaction2 in transaction_response %}
{% if transaction2.trade_sender_id == user.profile.id and transaction2.choice == None %}
<a aria-disabled="true" class='btn btn-warning' type="submit">Pending</a>
{% else %}

{% endif %}
{% endfor %}

card_project/cards/trading/templates/trading/sell_card.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
<ul class="messages">
    <h1>buy</h1>
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
    <h1>Trade</h1>
    <form method="POST">
        {% csrf_token %} 
        {{form.as_p}}
        <button class='btn btn-success' type="submit">Save</button>
    </form>
{% endblock %}

card_project/cards/trading/templates/trading/selling.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
    <h1>hello</h1>
    {% if user.is_authenticated %}
    <div class="container">
        <div class="row">
    {% for transaction in object_list %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Seller: {% if not transaction.seller == user.profile %}{{transaction.seller}}{% else %} You {% endif %}</h5>
                    <h5 class="card-title">Card: {{transaction.card}}</h5>
                    <h5 class="card-title">Base Price: {{transaction.card.price}}</h5>
                    <h5 class="card-title">Time Created: {{transaction.timestamp}}</h5>
                    {% if transaction.trade_choice == None %}
                    <a aria-disabled="true" class='btn btn-warning' type="submit">Pending</a>
                        {% if not transaction.seller == user.profile %}
                        <a href="{% url 'offer_card_status' transaction.id 'accept' %}" class='btn btn-success' name='a' type="submit">Accept</a>
                        <a href="{% url 'offer_card_status' transaction.id 'reject' %}" class='btn btn-danger' name='a' type="submit">Reject</a>
                        {% endif %}
                    {% elif transaction.trade_choice == 1 %}
                    <a href="#" aria-disabled="true" class='btn btn-success' type="submit">Accepted</a>
                    {% elif transaction.trade_choice == 0 %}
                    <a href="#" aria-disabled="true" class='btn btn-danger' type="submit">Rejected</a>
                    {% endif %}
                    {% if user.is_superuser %}
                    <a href="{% url 'delete_trade' transaction.id %}" class="btn btn-danger">Delete Trade</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endif %}

{% endblock %}

{% for transaction2 in transaction_response %}
{% if transaction2.trade_sender_id == user.profile.id and transaction2.choice == None %}
<a aria-disabled="true" class='btn btn-warning' type="submit">Pending</a>
{% else %}

{% endif %}
{% endfor %}

card_project/cards/trading/templates/trading/store.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
<h1>Store</h1>
<div class="container" style="min-width: 90vw;">
    
    <div class="row">
    {% for card in cards %}
        <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <ul>
                    {% if card.c_type == 'P' %}
                        <h5 class="card-title">Category: People</h5>
                    {% else %}
                        <h5 class="card-title">Category: Vehicles</h5>
                    {% endif %}
                    <p class="card-text">Name: {{card.store_card}}</p>
                    <p class="card-text">Rarity: {{card.store_card.rarity}}</p>
                    <p class="card-text">Id: {{card.store_card.id}}</p>
                    <p class="card-text">Price: {{card.store_card.price}}</p>
                    <p class="card-text">Score Needed: {{card.store_card.min_score_buy}}</p>
                </ul>
    
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="{% url 'buy_card_from_store' card.id %}" class="btn btn-success">Buy Card</a>
              {% if user.is_superuser %}
              <a href="{% url 'delete_card' card.id %}" class="btn btn-danger">Delete Card</a>
              {% endif %}
            </div>
          </div>
      {% endfor %}
    
    </div>
</div>

{% endblock %}

card_project/cards/trading/templates/trading/trade_details.html
{% extends 'base.html' %}

{% block content%}

<div class="container">
    <div class="row">
        {% for a in transaction.transactionresponse_set.all %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
            <h5 class="card-title">Sender: {{transaction.trade_sender}}</h5>
            <h5 class="card-title">Original Card: {{transaction.card}}</h5>
            <h5 class="card-title">offer Card: {{a.card}}</h5>
                {% if a.trade_choice == None %}
                        {% if transaction.trade_reciever == user.profile %}
                        <a aria-disabled="true" class='btn btn-warning' type="submit">Pending</a>
                        {% else %}
                        <a href="{% url 'trade_response_status' a.id 'accept' %}" class='btn btn-success' name='a' type="submit">Accept</a>
                        <a href="{% url 'trade_response_status' a.id 'reject' %}" class='btn btn-danger' name='a' type="submit">Reject</a>
                        {% endif %}
                {% elif a.trade_choice == 1 %}
                <a href="#" aria-disabled="true" class='btn btn-success' type="submit">Accepted</a>
                {% elif a.trade_choice == 0 %}
                <a href="#" aria-disabled="true" class='btn btn-danger' type="submit">Rejected</a>
                {% endif %}
        </div>
    {% endfor %}

    </div>

</div>
{% endblock %}

card_project/cards/trading/templates/trading/trade_response.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
    <h1>Trade</h1>
    <h3>Trade Reciever: {{trade_sender}}</h3>
    <h3>Tradeable Cards:</h3>
    <ul>
        {% for card in trade_options%}
        <li>{{card.name}}</li>
        {% endfor %}
    </ul>
    <form method="POST">
    {{form.error}}

        {% csrf_token %} 
        {{form.as_p}}

        <button class='btn btn-success' type="submit">Save</button>
    </form>
{% endblock %}